Remove sass styles and packages
WordPress/openverse-frontend pull request #1318
Opened 2022-04-23 15:20 UTC by obulat

## Fixes

Fixes #[issue number] by @[issue author]

## Description

## Testing Instructions

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-05-03 10:58 UTC, sarayourfriend requested changes
LGTM, just a couple things.

Can we also remove sass/scss entries from the following places, for consistency?

https://github.com/WordPress/openverse-frontend/blob/d6775aee4b921d8d3d158d5b3a213f81341bbe4f/nuxt.config.ts#L182

https://github.com/WordPress/openverse-frontend/blob/df16c251e8b543fd49af292f7067b7ac4797c3c5/jest.config.js#L21

https://github.com/WordPress/openverse-frontend/blob/a92edbf53e48c7733d74c6ce87a570cbc80b615a/.github/workflows/bundle_size.yml#L10

Also, the extension page layout is very broken now.
![image](https://user-images.githubusercontent.com/24264157/166441370-4e024311-8592-4d9f-8750-126605650afe.png)

Other than that I couldn't find any issues :tada: 

It does look like some of the layout shifted on the sources page and some other pages, but only very slightly. I agree they are minor and can be addressed later if there are discrepancies.

2022-05-03 10:58 UTC, sarayourfriend commented on package.json
> -    "sass-loader": "^10.2.1",
:tada: Yay!!!

2022-05-03 11:38 UTC, obulat commented
> LGTM, just a couple things.
> 
> Can we also remove sass/scss entries from the following places, for consistency?
> 
> https://github.com/WordPress/openverse-frontend/blob/d6775aee4b921d8d3d158d5b3a213f81341bbe4f/nuxt.config.ts#L182
> 
> https://github.com/WordPress/openverse-frontend/blob/df16c251e8b543fd49af292f7067b7ac4797c3c5/jest.config.js#L21
> 
> https://github.com/WordPress/openverse-frontend/blob/a92edbf53e48c7733d74c6ce87a570cbc80b615a/.github/workflows/bundle_size.yml#L10
> 
> Also, the extension page layout is very broken now. ![image](https://user-images.githubusercontent.com/24264157/166441370-4e024311-8592-4d9f-8750-126605650afe.png)
> 
> Other than that I couldn't find any issues 🎉
> 
> It does look like some of the layout shifted on the sources page and some other pages, but only very slightly. I agree they are minor and can be addressed later if there are discrepancies.

Ah, thank you for catching this! I did **_not_** look at the extension page.

2022-05-03 11:53 UTC, sarayourfriend commented
It'd be nice to have simple snapshot tests for each of the content pages, like the sources ones. Though now that you've removed the global styles I'm much less worried about them suddenly changing without us noticing!

2022-05-04 06:08 UTC, obulat commented on src/components/VCheckbox/meta/VCheckbox.stories.js
> +      window.alert('License checkbox checked. ' + JSON.stringify(params))
```suggestion
      window.alert('License checkbox checked! ' + JSON.stringify(params))
```

2022-05-05 18:56 UTC, panchovm approved these changes
Everything looks great to me. Nice work ✨

2022-05-05 19:01 UTC, obulat commented
Wow, I did not expect such an easy approval from you, @panchovm! Thank you!

2022-05-05 19:02 UTC, panchovm commented
I went through comparing the mockups and seeing if nothing is broken 😃

2022-05-05 19:03 UTC, obulat commented
@sarayourfriend, I've added the snapshots for content pages. I wonder if I should click on the translation bar 'Close' button for 'rtl' snapshots. The translation banner normally should not change, but if it does, there will be so many snapshots to update!

2022-05-06 07:48 UTC, sarayourfriend commented
@obulat That probably does make sense, you're right. As long as we have tests specifically targeting the translation banner then I think it's a good idea.

Once we have the UI state cookie in place we can simplify that as well by not having to click "close" on every test, we can just set the dismissed cookie at the top of the describe block.

2022-05-06 15:50 UTC, sarayourfriend approved these changes
LGTM! I had a weird thing happening where I wasn't able to see the back to top button but I am not able to reproduce it :shrug: Great work! This is such an exciting development.

2022-05-06 16:05 UTC, merged