Convert `duration` query parameter to `length` to match API
WordPress/openverse-frontend pull request #1442
Opened 2022-05-14 07:04 UTC by obulat

## Fixes

Fixes #[issue number] by @[issue author]

## Description

This is a companion PR to the API [PR#661](https://github.com/WordPress/openverse-api/pull/661). It renames the `duration` filter for audio with a `length` filter parameter, and adds `shortest` as a value.

## Testing Instructions

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-05-18 02:06 UTC, zackkrida commented
It looks like there's a translation string issue, @obulat 

![CleanShot 2022-05-17 at 22 05 31@2x](https://user-images.githubusercontent.com/6351754
/168942319-8ab33f69-0832-4cad-ac9e-7c6142c6bbec.png)

2022-05-19 19:22 UTC, dhruvkb requested changes

2022-05-19 19:48 UTC, zackkrida commented on src/locales/en.json
>      "durations": {
```suggestion
    "lengths": {
```

Good find, @dhruvkb

2022-05-20 06:59 UTC, obulat commented
Thank you for catching the issue, @zackkrida , and for finding the fix, @dhruvkb  :)

2022-05-20 07:19 UTC, dhruvkb approved these changes

2022-05-20 14:22 UTC, krysal approved these changes
LGTM!

2022-05-30 16:06 UTC, zackkrida commented
@obulat should this be merged now that WordPress/openverse-api#661 is merged and deployed?

2022-05-30 16:08 UTC, obulat commented
We probably need to re-index, because when I checked on Friday, the API wasn't returning length.

2022-05-30 16:26 UTC, zackkrida commented
Thanks @obulat I'll add this to our [community meeting agenda](https://docs.google.com/document/d/1AdcQVJy5B06J9N3jYCKk4GVKZZdyykjl4UP92kH_RpI/edit) for the 8th.

2022-06-16 22:18 UTC, krysal commented
@obulat Seems like we can unblock this now that the API v2.5.5 is deployed? 😮

E.g.: https://api.openverse.engineering/v1/audio/?q=love&length=long

2022-06-19 04:29 UTC, merged