Added design issue template
WordPress/openverse-frontend pull request #1733
Opened 2022-08-24 17:19 UTC by shreyanshmalvya

## Fixes

Fixes #1667 by @panchovm 

## Description

Added an issue template for design-related changes at : ```.github\ISSUE_TEMPLATE\design_changes.md```

## Testing Instructions

Reports no error upon executing ``` pnpm dev```

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-08-24 17:23 UTC, shreyanshmalvya commented
Should I add the label ```✨ goal: improvement``` as well to the template as they might be related to design improvements?

2022-08-24 17:25 UTC, sarayourfriend requested changes
Just one small typo fix but otherwise LGTM :)

2022-08-24 17:25 UTC, sarayourfriend commented on .github/ISSUE_TEMPLATE/design_changes.md
> +about: Propose design Changes
```suggestion
about: Propose design changes

```

2022-08-24 17:25 UTC, sarayourfriend commented
@shreyanshmalvya adding the improvement label makes sense to me. I say go for it :+1:

2022-08-24 17:36 UTC, shreyanshmalvya commented
I have fixed the typo and added the ```✨ goal: improvement``` label

2022-08-24 17:57 UTC, sarayourfriend approved these changes
LGTM. Thanks :rocket:

2022-08-25 17:54 UTC, shreyanshmalvya commented
@obulat could you please review this PR once.

2022-08-26 08:42 UTC, dhruvkb requested changes
Looks good to me, except this small textual change.

2022-08-26 08:42 UTC, dhruvkb commented on .github/ISSUE_TEMPLATE/design_changes.md
> +### Issues related
This bit confused me a little.

```suggestion
### Related issues

```

2022-08-26 08:47 UTC, dhruvkb approved these changes

2022-08-26 09:34 UTC, merged