Media Copy Update
WordPress/openverse-frontend pull request #1759
Opened 2022-08-30 12:55 UTC by ramadanomar

##Fixes
Fixes #1757 by @obulat.

##Description
I still have to add the icon to Get this Image/Audio button. Should i add a span with the icon inside or use VIconButton component?

2022-08-30 15:15 UTC, obulat reviewed
The updates to the "Get this <media>" were merged in https://github.com/WordPress/openverse-frontend/pull/1741, so you can remove them here.

2022-09-01 21:34 UTC, panchovm commented
Coming to say that the text must be "Visit the image’s website to download and use it" as suggested by @obulat

2022-09-02 00:30 UTC, ramadanomar commented
Hey @panchovm, the text should be good now. Thanks for confirming the change !

2022-09-02 01:26 UTC, zackkrida commented on src/components/VMediaInfo/VMediaReuse.vue
> +    <span class="text-base font-normal leading-[130%]">
```suggestion
    <p class="text-base font-normal leading-[130%]">
```

2022-09-02 01:26 UTC, zackkrida commented on src/components/VMediaInfo/VMediaReuse.vue
> +    </span>
```suggestion
    </p>
```

2022-09-02 01:32 UTC, zackkrida commented on src/locales/en.json
> +      "description": "Visit the {media}'s website to download and to use it. Make sure to credit the creator by showing the attribution information where you are sharing your work.",
```suggestion
      "description": "Visit the {media}'s website to download and use it. Make sure to credit the creator by showing the attribution information where you are sharing your work.",
```

2022-09-02 01:32 UTC, zackkrida requested changes
Some small fixes, but looks nice.

2022-09-05 02:45 UTC, obulat approved these changes
LGTM!

2022-09-05 13:53 UTC, zackkrida approved these changes

2022-09-05 15:34 UTC, obulat commented
I am going to fix Playwright test failures and merge this PR, @ramadanomar.

2022-09-05 15:57 UTC, panchovm commented
I am seeing one style mistake.

On mobile, the descriptive paragraph below section title is font-size `14px` and line-height `18px` instead of `14px` and `18px` respectively, as `Label regular` style was defined.

2022-09-05 17:42 UTC, merged