update search term when navigating with browser`s back and forward buttons
WordPress/openverse-frontend pull request #2101
Opened 2023-01-16 11:42 UTC by anton202

## Fixes

Fixes #2082  by @obulat 

## Description

implemented the steps that described in the issue:
* add query param with the searcn term to the url of the single result page
* update search term that is saved in the store when navigating from search page 

now, when doing a search from a single result page and then going back with the browser button 
the search term in the header will be set correctly.

<b>The curent State of staging</b>

https://user-images.githubusercontent.com/29175506/212668428-c1ed8f6f-734a-4678-be2a-206e06d89ade.mp4

<b>This pull request</b>

https://user-images.githubusercontent.com/29175506/212669005-ed3fbb7e-fc34-4197-9032-23e3212a750e.mp4

## Testing Instructions
Follow the steps in the video :)
also, try this steps with an audio result

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-01-16 14:50 UTC, obulat reviewed
This looks really good, @anton202! Do you think you could add an e2e test?

2023-01-16 15:11 UTC, anton202 commented
@obulat sure

2023-01-26 09:09 UTC, anton202 commented
i dont know why the e2e/homepage.spec.ts test is failing... i didnt changed anything related with that test. but anyway, i`ve changed the css selector of the search type pop over, in that test and now it dose pass.

regarding the e2e/translation-banner.spec.ts 
when i run all the tests, this test fail
when i run only this test, it pass

2023-01-31 06:49 UTC, obulat requested changes
It works beautifully, @anton202! And the tests are 💯 

One request I have is to change the `searchTerm` to be a prop for `VImageCellSquare`/`VAudioTrack`/ `VImageCell`, and actually get it from the `searchStore` in the parent components. This way, the `searchStore.searchTerm` will be called once for each of the media items, and the `Cell`/`Track` components will not need to import the `useSearchStore`.

2023-02-03 09:15 UTC, anton202 commented
sure, you rigth :)

2023-02-08 14:45 UTC, obulat approved these changes
Awesome work, thank you, @anton202! Thank you for adding the changes and the test for them!
I've rebased your branch onto main and force-pushed it, so now the CI is green.

2023-02-08 15:06 UTC, anton202 commented
@obulat Thank you :)

2023-02-08 15:08 UTC, anton202 commented on test/playwright/e2e/search-navigation.spec.ts
> +    test("search term should be set to the search query param on an image type single result page", async ({
so, does this test pass now?

2023-02-08 22:02 UTC, zackkrida approved these changes
This appears to be working perfectly. Great work @anton202

2023-02-08 22:02 UTC, merged