Add Debounce to filter selection
WordPress/openverse-frontend pull request #2104
Opened 2023-01-18 12:29 UTC by anton202

## Fixes

Fixes #505 by @sarayourfriend 

## Description
as described in the issue by @sarayourfriend, currently when selecting several filters one after the other
a query will be excuted for each filter selection.
so, as suggested in the issue i added a debounce of 500ms to filter selection (basically switched the watch function to watchDebounced )

<b>Staging</b>

https://user-images.githubusercontent.com/29175506/213170688-53d17a10-0bb6-4039-88e6-88bd50cfa0bf.mp4

<b>This PR</b>

https://user-images.githubusercontent.com/29175506/213171268-41363f93-a314-4d4f-8644-e3d18fb12bb7.mp4

## Testing Instructions

follow the steps in the video :)

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-01-19 09:52 UTC, anton202 commented
Hi, @zackkrida 
i`m having a wierd thing with e2e/mobile-menu-old.spec.ts test.
currently it fails, it fails also when i run it locally.
but, if i set the new_header:{status:{staging:disabled}} at features-flags.json
the test dose pass.
maybe its something related to ` enableOldHeader` function at the e2e/mobile-menu-old.spec.ts test ?

2023-01-19 22:44 UTC, sarayourfriend commented
@obulat would probably know best how to debug this issue quickly :crossed_fingers:

2023-01-20 06:51 UTC, obulat commented
@anton202, I think you opened this PR before the `new_header` flag was set to be `on` by default in the staging environment. So, in your branch, `new_header.status.staging` in `features-flags.json` is set to `switchable`, and the `defaultValue` is `off`, but in `main` it was changed to `on`. You will probably need to rebase onto (updated) main branch to fix the problems.

If there are still problems with the e2e remaining, I think we will also need to change the `enableOldHeader` function, just like you mentioned.

I tried rebasing your branch onto main, and changing the functions to what's listed below, and didn't get any errors in e2e tests locally.  

```
--- a/test/playwright/utils/navigation.ts
+++ b/test/playwright/utils/navigation.ts
@@ -464,19 +464,12 @@ export const enableNewHeader = async (page: Page) => {
 
 export const enableOldHeader = async (page: Page) => {
   // Add the new_header cookie
-  await page.context().addCookies([
-    {
-      name: "features",
-      value: "%7B%22new_header%22%3A%22off%22%7D",
-      domain: "localhost",
-      path: "/",
-    },
-  ])
+  await setCookies(page.context(), { features: { new_header: "off" } })
 }
 
 export const setCookies = async (
   context: BrowserContext,
-  cookies: Record<string, string | boolean | string[]>
+  cookies: Record<string, string | boolean | string[] | Record<string, string>>
 ) => {
   await context.addCookies(
     Object.entries(cookies).map(([name, value]) => ({
```

2023-01-20 06:55 UTC, obulat requested changes
Thank you for your fix, @anton202, it works perfectly! I've added notes about the tests, and I'll approve after they are fixed.

2023-01-20 07:18 UTC, anton202 commented
@obulat Thank you for the help. i`ll adress that on sunday :)

2023-01-21 08:58 UTC, zackkrida commented on test/playwright/e2e/search-navigation-old.spec.ts
> +    //we need to wait for the page to get reloaded before procceding the test
```suggestion
    // we need to wait for the page to reload before running the test
```

here is a small grammatical suggestion

2023-01-21 08:58 UTC, zackkrida commented on test/playwright/e2e/search-navigation.spec.ts
> +      //we need to wait for the page to get reloaded before procceding the test
```suggestion
      // we need to wait for the page to reload before running the test
```

2023-01-22 13:48 UTC, zackkrida commented on src/components/VFilters/VSearchGridFilter.vue
> +      { debounce: 500, maxWait: 5000 }
After playing with this a little, I think something like 1000 or 800 ms for the 	`debounce` value might work better and cover more cases, including situations where a user is selecting multiple filters in a row. For example, choosing multiple sources.

2023-01-22 14:34 UTC, anton202 commented
@obulat i\`ve tried your suggestion but the test still didnt pass :(
i did noticed though that on this branch and on the main branch `new_header.status.staging` is set to `enabled`
i changed it to `switchable` and now the test passing.
btw, right now we can\`t toggle betwen the new and old header on staging. i think beacuse `new_header.status.staging` is set to  `enabled`

2023-01-24 15:34 UTC, anton202 commented
weird. all the tests pass when i run them locally
![debounce-tests](https://user-images.githubusercontent.com/29175506/214336975-82060b58-e602-48c9-bb90-94377845df29.png)

2023-01-24 23:23 UTC, sarayourfriend commented
@anton202 Sorry for the delay in responses on this PR, folks have been travelling the past week and doing work offline. Most will be back later in the week and someone will be able to help debug more closely. Appreciate the patience :pray:

2023-01-26 08:21 UTC, anton202 commented
sure, no problem :)

2023-01-31 10:31 UTC, obulat approved these changes

2023-02-08 04:33 UTC, dhruvkb approved these changes
LGTM and it works. But I have a question about the wait numbers. A code comment `//` explaining them would be good.

2023-02-08 04:33 UTC, dhruvkb commented on src/components/VFilters/VSearchGridFilter.vue
> +      { debounce: 800, maxWait: 5000 }
What is the reasoning behind these values?

2023-02-08 04:35 UTC, dhruvkb commented on src/components/VFilters/VSearchGridFilter.vue
> +      { debounce: 800, maxWait: 5000 }
Ah I see @zackkrida wanted to raise it from 500. 800 seemed a very specific, very arbitrary choice to start with.

2023-02-08 06:37 UTC, merged