Url camecase fix
WordPress/openverse-frontend pull request #262
Opened 2021-09-24 06:44 UTC by theshakeabhi

## Fixes
Fixes #254   by @dhruvkb 

## Description
This PR would make the prop name uniform across the code base by changing the non-camelcase to camel case.
For now these changes has been made across the code base:
`ccLicenseURL to ccLicenseUrl`
`licenseURL to licenseUrl`
`openverseLicenseURL to openverseLicenseUrl`

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-09-24 10:13 UTC, obulat commented on src/components/ImageDetails/ImageAttribution.vue
> +    ccLicenseUrl: String,
```suggestion
    openverseLicenseUrl: String,
```

2021-09-24 10:14 UTC, obulat commented on src/components/ImageDetails/ImageAttribution.vue
> +      return `${this.ccLicenseUrl}&atype=rich`
```suggestion
      return `${this.openverseLicenseUrl}&atype=rich`
```

2021-09-24 10:14 UTC, obulat commented on src/components/ImageDetails/ImageInfo.vue
> +    'ccLicenseUrl',
```suggestion
    'openverseLicenseUrl',
```

2021-09-24 10:14 UTC, obulat commented on src/components/ImageDetails/PhotoDetails.vue
> +            :cc-license-u-r-l="openverseLicenseUrl"
```suggestion
            :openverse-license-url="openverseLicenseUrl"
```

2021-09-24 10:14 UTC, obulat commented on src/components/ImageDetails/PhotoDetails.vue
> +            :cc-license-u-r-l="openverseLicenseUrl"
```suggestion
            :openverse-license-url="openverseLicenseUrl"
```

2021-09-24 10:15 UTC, obulat commented on src/components/MediaInfo/MediaReuse.vue
> +        :license-u-r-l="licenseUrl"
```suggestion
        :license-url="licenseUrl"
```

2021-09-24 10:15 UTC, obulat commented on src/components/MediaInfo/MediaReuse.vue
> +        :license-u-r-l="licenseUrl"
```suggestion
        :license-url="licenseUrl"
```

2021-09-24 10:15 UTC, obulat commented on src/pages/audio/_id.vue
> +      :license-u-r-l="openverseLicenseUrl"
```suggestion
      :license-url="openverseLicenseUrl"
```

2021-09-24 10:16 UTC, obulat commented on src/utils/attribution-html.js
> +function attributionHtml(image, ccLicenseUrl, fullLicenseName) {
```suggestion
function attributionHtml(image, openverseLicenseUrl, fullLicenseName) {
```

2021-09-24 10:16 UTC, obulat commented on src/utils/attribution-html.js
> +  const licenseLink = ` is licensed under <a href="${ccLicenseUrl}" style="margin-right: 5px;">${fullLicenseName.toUpperCase()}</a>`
```suggestion
  const licenseLink = ` is licensed under <a href="${openverseLicenseUrl}" style="margin-right: 5px;">${fullLicenseName.toUpperCase()}</a>`
```

2021-09-24 10:16 UTC, obulat commented on src/utils/attribution-html.js
> +  const licenseImgLink = `<a href="${ccLicenseUrl}" target="_blank" rel="noopener noreferrer" style="display: inline-block;white-space: none;margin-top: 2px;margin-left: 3px;height: 22px !important;"
```suggestion
  const licenseImgLink = `<a href="${openverseLicenseUrl}" target="_blank" rel="noopener noreferrer" style="display: inline-block;white-space: none;margin-top: 2px;margin-left: 3px;height: 22px !important;">${licenseIcons}</a>`
```

2021-09-24 10:17 UTC, obulat commented on test/unit/specs/components/ImageDetails/copy-license.spec.js
> +      ccLicenseUrl: 'http://license.com',
```suggestion
      openverseLicenseUrl: 'http://license.com',
```

2021-09-24 10:17 UTC, obulat commented on test/unit/specs/components/ImageDetails/image-attribution.spec.js
> +      ccLicenseUrl: 'http://license.com',
```suggestion
      openverseLicenseUrl: 'http://license.com',
```

2021-09-24 10:17 UTC, obulat commented on test/unit/specs/components/ImageDetails/image-info.spec.js
> +      ccLicenseUrl: 'http://license.com',
```suggestion
      openverseLicenseUrl: 'http://license.com',
```

2021-09-24 10:19 UTC, obulat requested changes
Thank you for your PR!
There are several changes I've added inline: it's better to finish renaming `ccLicenseUrl` to `openverseLicenseUrl`, and rename prop names, as well as values.

2021-09-24 10:19 UTC, obulat commented on src/assets/fonts/VocabularyIcons.json
> +        "licenseUrl": "https://opensource.org/licenses/MIT"
We don't need to change anything in this file.

2021-09-24 10:27 UTC, obulat commented on src/components/ImageDetails/ImageAttribution.vue
> +      :license-u-r-l="licenseUrl"
```suggestion
      :license-url="licenseUrl"
```

2021-09-24 10:28 UTC, obulat commented on src/components/ImageDetails/ImageAttribution.vue
> +      :license-u-r-l="licenseUrl"
```suggestion
      :license-url="licenseUrl"
```

2021-09-24 10:38 UTC, obulat commented on src/assets/fonts/VocabularyIcons.json
> +        "licenseUrl": "https://opensource.org/licenses/MIT"
```suggestion
        "licenseURL": "https://opensource.org/licenses/MIT"
```

2021-09-24 10:38 UTC, obulat commented on src/assets/fonts/VocabularyIcons.json
> +            "licenseUrl": "https://opensource.org/licenses/MIT"
```suggestion
            "licenseURL": "https://opensource.org/licenses/MIT"
```

2021-09-24 10:39 UTC, obulat commented on src/assets/fonts/VocabularyIcons.json
> +        "licenseUrl": "https://opensource.org/licenses/MIT"
```suggestion
        "licenseURL": "https://opensource.org/licenses/MIT"
```

2021-09-24 11:26 UTC, obulat commented on src/components/ImageDetails/ImageAttribution.vue
> +    openverseLicenseUrl: String,
```suggestion
    licenseUrl: String,
```

2021-09-24 11:27 UTC, obulat commented on src/components/ImageDetails/ImageAttribution.vue
> +      return `${this.openverseLicenseUrl}&atype=rich`
```suggestion
      return `${this.licenseUrl}&atype=rich`
```

2021-09-24 11:28 UTC, obulat commented on src/components/ImageDetails/ImageAttribution.vue
> +    licenseUrl() {
```suggestion
    licenseUrlRichText() {
```

2021-09-24 11:28 UTC, obulat commented on src/components/ImageDetails/ImageAttribution.vue
> +      :license-url="licenseUrl"
```suggestion
      :license-url="licenseUrlRichText"
```

2021-09-24 11:29 UTC, obulat commented on src/components/ImageDetails/ImageAttribution.vue
> +      :license-url="licenseUrl"
```suggestion
      :license-url="licenseUrlRichText"
```

2021-09-24 11:29 UTC, obulat commented on src/components/ImageDetails/ImageInfo.vue
> +    'openverseLicenseUrl',
```suggestion
    'licenseUrl',
```

2021-09-24 11:29 UTC, obulat commented on src/components/ImageDetails/PhotoDetails.vue
> +            :openverse-license-url="openverseLicenseUrl"
```suggestion
            :license-url="licenseUrl"
```

2021-09-24 11:30 UTC, obulat commented on src/components/ImageDetails/PhotoDetails.vue
> +            :openverse-license-url="openverseLicenseUrl"
```suggestion
            :license-url="licenseUrl"
```

2021-09-24 11:30 UTC, obulat commented on src/components/ImageDetails/PhotoDetails.vue
> +    openverseLicenseUrl() {
```suggestion
    licenseUrl() {
```

2021-09-24 11:30 UTC, obulat commented on src/components/MediaInfo/CopyLicense.vue
> +              :href="openverseLicenseUrl"
```suggestion
              :href="licenseUrl"
```

2021-09-24 11:30 UTC, obulat commented on src/components/MediaInfo/CopyLicense.vue
> +              <template v-if="openverseLicenseUrl" #URL>
```suggestion
              <template v-if="licenseUrl" #URL>
```

2021-09-24 11:31 UTC, obulat commented on src/components/MediaInfo/CopyLicense.vue
> +                {{ openverseLicenseUrl }}
```suggestion
                {{ licenseUrl }}
```

2021-09-24 11:31 UTC, obulat commented on src/components/MediaInfo/CopyLicense.vue
> +    openverseLicenseUrl: String,
```suggestion
    licenseUrl: String,
```

2021-09-24 11:31 UTC, obulat commented on src/pages/audio/_id.vue
> +    openverseLicenseUrl() {
```suggestion
    licenseUrl() {
```

2021-09-24 11:32 UTC, obulat commented on src/pages/audio/_id.vue
> +      :license-url="openverseLicenseUrl"
```suggestion
      :license-url="licenseUrl"
```

2021-09-24 11:32 UTC, obulat commented on src/pages/audio/_id.vue
> +      const licenseUrl = `${this.openverseLicenseUrl}&atype=html`
```suggestion
      const licenseUrl = `${this.licenseUrl}&atype=html`
```

2021-09-24 11:32 UTC, obulat commented on src/utils/attribution-html.js
> +function attributionHtml(image, openverseLicenseUrl, fullLicenseName) {
```suggestion
function attributionHtml(image, licenseUrl, fullLicenseName) {
```

2021-09-24 11:33 UTC, obulat commented on src/utils/attribution-html.js
> +  const licenseLink = ` is licensed under <a href="${openverseLicenseUrl}" style="margin-right: 5px;">${fullLicenseName.toUpperCase()}</a>`
```suggestion
  const licenseLink = ` is licensed under <a href="${licenseUrl}" style="margin-right: 5px;">${fullLicenseName.toUpperCase()}</a>`
```

2021-09-24 11:33 UTC, obulat commented on src/utils/attribution-html.js
> +  const licenseImgLink = `<a href="${openverseLicenseUrl}" target="_blank" rel="noopener noreferrer" style="display: inline-block;white-space: none;margin-top: 2px;margin-left: 3px;height: 22px !impo
```suggestion
  const licenseImgLink = `<a href="${licenseUrl}" target="_blank" rel="noopener noreferrer" style="display: inline-block;white-space: none;margin-top: 2px;margin-left: 3px;height: 22px !important;">${licenseIcons}</a>`
```

2021-09-24 11:33 UTC, obulat commented on test/unit/specs/components/ImageDetails/copy-license.spec.js
> +      openverseLicenseUrl: 'http://license.com',
```suggestion
      licenseUrl: 'http://license.com',
```

2021-09-24 11:33 UTC, obulat commented on test/unit/specs/components/ImageDetails/image-attribution.spec.js
> +      openverseLicenseUrl: 'http://license.com',
```suggestion
      licenseUrl: 'http://license.com',
```

2021-09-24 11:33 UTC, obulat commented on test/unit/specs/components/ImageDetails/image-info.spec.js
> +      openverseLicenseUrl: 'http://license.com',
```suggestion
      licenseUrl: 'http://license.com',
```

2021-09-24 11:37 UTC, obulat approved these changes

2021-09-24 11:49 UTC, zackkrida approved these changes

2021-09-28 13:14 UTC, merged

2021-09-28 13:14 UTC, zackkrida commented
Thank you @theshakeabhi !