Update about and sources pages
WordPress/openverse-frontend pull request #90
Opened 2021-07-09 21:21 UTC by krysal

Fixes #34.

## Description 
This PR remove the sources table in `/about` page and expand the one in the `/sources` page, as presented in @panchovm's [mockups][mockups] for transitional styles. Also updates the links to the Make WordPress team and to suggest new sources to the Catalog.

[mockups]: https://www.figma.com/file/BlUTIXRHLOq5mRITpDpi3E/Transitional-styles?node-id=0%3A1&viewport=74%2C344%2C0.09312169253826141

## Preview
https://ov-fe-preview.herokuapp.com/sources

2021-07-12 14:19 UTC, panchovm commented
It looks excellent. I have some minor comments:
1. The title "We appreciate suggestions…" is in `h5`, it should be `h3`.
2. `h3` font size is `23px`, it should be `19px`. 
3. This style update is no longer using a `body-big` style. We should use the default paragraph style.
4. Related to the prior point, default paragraph looks slightly tight compared to mockup. I'd suggest a `1.8` for `line-height` to have more space between lines.
5. The "Suggest a new source" button is all capitals and text bigger than the mockup. I think this is part of `button` class. We should update all buttons to match the mockup. 
6. Table should have a `4px` as `border-radius`.

## Additional comments
The `:hover` style of default link should not change its color but add the underline style

<img width="313" alt="Screen Shot 2021-07-12 at 10 07 03" src="https://user-images.githubusercontent.com/895819/125301432-fd0a2780-e2f8-11eb-8951-5b79fba84c6b.png">

2021-07-12 14:29 UTC, panchovm requested changes
I added a comment indicating some minor tweaks

2021-07-12 22:56 UTC, krysal commented
Thanks for pointing these details @panchovm. I updated the styles as requested, except for titles. Setting `line-height: 1.9` gives exactly the value shown in mockups (`30.4px`). The button and table should have more accurate styles too.

The "We appreciate suggestions…" title is now an `h3` but as you can see, it's now bigger than the previous titles which are semantically `h3` but showing instead styles of an `h4` because the `title is-4` classes.

Currently, the title sizes are:
```scss
$font-size-h1: 3.56rem;
$font-size-h2: 2.25rem;
$font-size-h3: 1.75rem;   // ==> 28px
$font-size-h4: 1.43rem;   // ==> 22.88px
$font-size-h5: 1.25rem;   // ==> 20px
$font-size-h6: 1.12rem;   // ==> 17.92px
```
So should we update all title sizes? or just make `<h3 class="title subtitle is-5 ...">...</h3>`? `is-5` is the closest to 19px for now.

The[ preview URL](https://ov-fe-preview.herokuapp.com/sources) is the same.

2021-07-13 14:28 UTC, panchovm commented
We should update the title styles. The audio integration version might change it again, but I will make sure of pointing what changed and what's new. If the change impacts too much the transitional version, then we can skip it.

2021-07-13 14:30 UTC, panchovm reviewed
If we can update the title styles without a significant problem, then let's go with that.

2021-07-13 21:21 UTC, krysal commented
> If we can update the title styles without a significant problem, then let's go with that.

We can, so I did it! I added specific changes to the `<h3>` titles and the button of the Sources page, both have the correct font size now. We can change global styles when the design with the audio integration is ready.

This is ready for another review.

2021-07-14 13:56 UTC, panchovm approved these changes
It looks excellent. Great work

2021-07-17 05:07 UTC, dhruvkb approved these changes
This is looking really good.

2021-07-19 14:26 UTC, merged